server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location = /CarolynElaine {
    return 301 /carolyn-elaine/;
  }

  location = /CarolynElaine/ {
    return 301 /carolyn-elaine/;
  }

  location = /carolynelaine {
    return 301 /carolyn-elaine/;
  }

  location = /carolynelaine/ {
    return 301 /carolyn-elaine/;
  }

  location / {
    try_files $uri $uri/ =404;
  }
}
